### ISSUE TITLE
TP5_EJ12 (LocalDateInterval)

### ISSUE THREAD

**Issue by facundokrens65049** [POO-ITBA/2024_02#13]
Hola! Buenas noches. Tengo una consulta puntual sobre el ejercicio 12 (LocalDateInterval) de la Guía 5. Tal y como se plantea en la solución, para la funcion hasNext() del iterador se plantea que la fecha _current_ debe ser anterior/posterior (según el signo del step) a la fecha _to_. Lo correcto no sería, en vez, chequear que _current.plusDays(step)_ cumpla con dicho criterio? Por ejemplo, si el intervalo es de 2 días, el día _current_ es 17 y el dia _to_ es 18, hasNext() va a retornar _true_, sin embargo, no hay un valor siguiente dentro del intervalo.

```c
import java.time.LocalDate;
import java.util.Iterator;
import java.util.NoSuchElementException;

public class LocalDateInterval implements Iterable<LocalDate>{

    private LocalDate from;
    private LocalDate to;
    private int interval;

    public LocalDateInterval(LocalDate from, LocalDate to, int interval){
        this.from = from;
        this.to = to;
        this.interval = interval;
    }

    @Override
    public Iterator<LocalDate> iterator(){
        return new LocalDateIterator();
    }

    @Override
    public String toString(){
        return iterator().toString();
    }

    private class LocalDateIterator implements Iterator<LocalDate> {

        private LocalDate current = from; // se inicializa en from.

        @Override
        public boolean hasNext(){
            return ((interval > 0 && !current.isAfter(to))
                    || (interval < 0 && !current.isBefore(to)));
        }

        @Override
        public LocalDate next(){
            if(!hasNext()){
                throw new NoSuchElementException();
            }
            LocalDate aux = current;
            current = current.plusDays(interval);
            return aux;
        }
    }


}

**Comment by fmeola** [comment]
Hola @facundokrens65049 
Pensá que en current ya tenés listo el LocalDate que vas a devolver (el que actualizó la última invocación a next y todavía no se retornó) así que si en el hasNext hacés la comprobación current.plusDays(step) te estás adelantando un elemento de la iteración.

**Comment by facundokrens65049** [comment]
Perfecto, gracias!
