### ISSUE TITLE
TP5_Ejer3

### ISSUE THREAD

**Issue by pedrogonzaleznunez** [POO-ITBA/2024_02#15]
Buenas que tal, me esta costando entender el como funciona el **`next()`** en este iterador ciclico.

```java
@Override
    public Pair<E> next(){
        if(!hasNext()){
            throw new NoSuchElementException();
        }
        E left, right;

        // si la coleccion iterable, NO tiene ningun objeto
        // entonces tengo que crear uno nuevo
        //entonces el left va a ser ese "iterador+1"

        if(!iterator.hasNext()) {
            iterator = collection.iterator();
        }

        left = iterator.next();

        if(!iterator.hasNext()) {
            iterator = collection.iterator();
        }
        right = iterator.next();
        return new Pair<>(left, right);
    }
```

**Comment by fmeola** [comment]
Hola @pedrogonzaleznunez 
Entiendo que es el Ejercicio 3 del TP6
Este iterador depende de la implementación de los iteradores que ya tienen las colecciones de Java. Cuando hacés collection.iterator() le estás pidiendo por ejemplo a la ArrayList o al HashSet un nuevo iterador para recorrer todos los elementos de esa colección desde el principio. Eso te lo guardás en la variable de instancia iterator.
Como para este ejercicio se pide devolver de a par de elementos se consigue primero el elemento de la izquierda y luego el de la derecha. 
Si el iterador que tenés guardado en la variable de instancia todavía tiene elementos lo usás para conseguir el elemento de la izquierda. Y si se quedó sin elementos pedís un iterador nuevo (como si lo reiniciaras) y ahí pedís el primero de nuevo para que sea el elemento de la izquierda. 
Lo mismo se repite para el elemento de la derecha (si hay elementos se obtiene uno con next y si no hay mas elementos se obtiene uno nuevo y se obtiene el primero con next).

**Comment by pedrogonzaleznunez** [comment]
Perfecto Franco, quedó todo claro. Muchas gracias
