### ISSUE TITLE
Repaso 2do Parcial - Ej1

### ISSUE THREAD

**Issue by pedrogonzaleznunez** [POO-ITBA/2024_02#18]
Buenas, no entiendo por qué me saltan los siguientes errores en el tester.

<img width="956" alt="Captura de pantalla 2024-10-25 a las 12 43 27" src="https://github.com/user-attachments/assets/b3d835cb-0865-4826-b711-74c252aba9c4">

------------------------------------------------------------------------------------------
Esto fue lo que implementé:

> ../SimpleArrayList.java

```java
public class SimpleArrayList<E> extends ArrayList<E> implements SimpleList<E>{

    @Override
    public <K> Map<K, E> toMap(Function<E, K> keyMapper) {
        Map<K,E> map = new HashMap<>();
        for(E element : this) {
            map.putIfAbsent(keyMapper.apply(element), element);
        }
        return map;

    }
}
```

> ../SimpleList.java

```java
public interface SimpleList <E> extends List<E> {

    <K> Map<K,E> toMap(Function<E, K> keyMapper);

}
```

**Comment by fmeola** [comment]
Hola @pedrogonzaleznunez 
Tanto la interfaz como la implementación se ven perfectas.
Me parece que es un tema de imports, fijate si estás usando los imports del paquete java.util. Quizás en ves de usar java.util.ArrayList estás usando una ArrayList que hiciste en el taller. También puede ser un error del IDE, probá corriéndolo a ver si obtenés ese mismo mensaje como error de compilación.
Sino copiame los tres .java completos y lo miro.

**Comment by pedrogonzaleznunez** [comment]
Revisé nuevamente y faltaba en import del Map en el tester, no me habia dado cuenta. Muchas gracias.
