### ISSUE TITLE
2022_1Q (ejer3)

### ISSUE THREAD

**Issue by pedrogonzaleznunez** [POO-ITBA/2024_02#24]
Buenas, queria saber si estaba bien mi solución.Muchas Gracias

[Ejer3.zip](https://github.com/user-attachments/files/17639490/Ejer3.zip)

**Comment by fmeola** [comment]
Hola @pedrogonzaleznunez 
Paso a comentar:

# Booking

Fijate que en `Booking` se pide el siguiente orden

> en orden cronológico y desempata alfabéticamente por nombre de atracción

así que donde dice

```ruby
    def <=>(other)
        return nil unless other.is_a? Booking
        [@name,@date] <=> [other.name, other.date]
    end
```

debe decir

```ruby
    def <=>(other)
        return nil unless other.is_a? Booking
        [@date, @name] <=> [other.date, other.name]
    end
```

En el tester fijate que sobre cada instancia de `Booking` se invoca a `p` en vez de `puts` así que deberías sobreescribir el `inspect`

Por último en `Booking` no necesitás `accesor`, sólo `reader` ya que sólo usás los getters para el `<=>`.

# Excepciones

Tenés invertidos los mensajes de los `raise` entre `Bookings_two` y `Bookings_three`

Cuando hacés

```ruby
        raise 'Reached max' unless @allowed_attrc.include?(attraction)
```

no estás lanzando la excepción esperada (la que creaste). Debería ser

```ruby
        raise BookingException unless @allowed_attrc.include?(attraction)
```

# Bookings_three

No corresponde invocar a `ex?` en `book` porque ya lo hará `super` cuando se ejecute el método `book` de `Bookings_two`

Falta indicar el parámetro en la invocación a `validCity?`

**Comment by pedrogonzaleznunez** [comment]
Perfecto Franco, muchisimas gracias por tu tiempo
