### ISSUE TITLE
Pregunta sobre solución Rec2023_2Q - Ejer3

### ISSUE THREAD

**Issue by pedrogonzaleznunez** [POO-ITBA/2024_02#38]
Buenas, queria saber por que en este caso no se agregó la linea 
```ruby 
alias_method :eql? , :==
```
Es siempre necesario hacerlo ? O es por algo que no estoy viendo?

<img width="1050" alt="Screenshot 2024-11-27 at 18 23 52" src="https://github.com/user-attachments/assets/9c70f997-52b0-4e9b-8b46-39b600563d27">

Muchas gracias
Saludos

**Comment by pedrogonzaleznunez** [comment]
Lo mismo me pasa con el hash.
En algunas soluciones veo que se implementa el == pero el hash no. 
Segun tengo entendido, van siempre de la mano

**Comment by fmeola** [comment]
Hola @pedrogonzaleznunez 
No es así.
En este ejercicio como tenés un Array de AquariumReservation y se usan métodos para saber si un elemento pertenece al array (como include? o delete) Ruby sólo usa el == para recorrer el array y encontrar uno equivalente 
Distinto es cuando tenés un Set de AquariumReservation o un Hash donde las claves son de tipo AquariumReservation. Ahí si Ruby exige hash y eql? porque por atrás estás usando una tabla de hash.

**Comment by pedrogonzaleznunez** [comment]
Perfecto Franco, muchas gracias
