### ISSUE TITLE
TP 1 

### ISSUE THREAD

**Issue by juan43963** [POO-ITBA/2024_02#4]
Buenas, hasta que ejercicio podemos hacer de la primer guia? 
Saludos!

**Comment by fmeola** [comment]
Hola @juan43963 
Pueden hacer hasta el ejercicio 4 inclusive.
Luego de cada miércoles les voy a ir indicando en la carpeta de Campus hasta qué ejercicio pueden hacer.

![Captura de pantalla 2024-08-09 a la(s) 15 23 53](https://github.com/user-attachments/assets/0d6e2fdf-b7ad-4a8b-94b6-5dfdf3a00d2e)

**Comment by juan43963** [comment]
buenisimo! gracias!
