### ISSUE TITLE
2.2 Voltear

### ISSUE THREAD

**Issue by OctavioNRS** [POO-ITBA/2024_02#43]
Una consulta con respecto a la funcionalidad del botón voltear.
Dado el ejemplo en el enunciado, si fuesemos a voltear una figura por segunda vez ¿deberia volver a la posicion inicial o seguir moviendose en la dirección que corresponda (segun si es horizontal o vertical)?
De volver a la posicion inicial, ¿deberiamos conservar el estado "volteado" (true/false) de dicha figura al voltearse?

En la consigna solamente aclara al hacer una única vez la operación de voltear y no cómo seria el caso de operaciones de voltear sucesivas.

Muchas gracias

**Comment by fmeola** [comment]
Hola @OctavioNRS 
Debería seguir moviéndose en la dirección que corresponda.
