### ISSUE TITLE
Duda funcionalidad 3

### ISSUE THREAD

**Issue by dalilaorbaj** [POO-ITBA/2024_02#50]
Hola! Queria consultar sobre un detalle de la funcionalidad 3. 
Esta bien que cuando una capa esta oculta se pueda dibujar en esa capa y no se vea lo que se dibuja pero despues al mostrar la capa se puedan ver las figuras dibujadas mientras estaba oculta? 
Y esta bien que el cursor, cuando una capa esta oculta, no muestre que hay una figura cuando se hace hover sobre la misma?
Desde ya, muchas gracias!!

**Comment by fmeola** [comment]
Hola @dalilaorbaj 
Eso no se especifica en el enunciado así que pueden tomar ustedes la decisión que prefieran.

**Comment by dalilaorbaj** [comment]
Buenisimo gracias!
